from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait

driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(20)
driver.get("https://training.pfms.gov.in/SitePages/Users/LoginDetails/Login.aspx")
time.sleep(5)
Username = driver.find_element(By.ID,"UserName")
Username.send_keys("dlin00001984")
Passcode = driver.find_element(By.ID,"Password")
Passcode.send_keys("root@123")
actions = ActionChains(driver)
actions.scroll_by_amount(0,300).perform()
time.sleep(10)
Login = driver.find_element(By.XPATH,"//input[@value='Log In']")
Login.click()
time.sleep(2)
actions.move_to_element(driver.find_element(By.LINK_TEXT,'Agency')).perform()
time.sleep(2)
Agency_Registeration = driver.find_element(By.LINK_TEXT, "Agency Registration")
Agency_Registeration.click()
Type_of_Registration = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$ddlTypeofRegistration")
option = Select(Type_of_Registration)
option.select_by_value("1/01")
time.sleep(2)
Pan = driver.find_element(By.ID, "ctl00_ctl00_cphBody_cphBody_chkPanNO")
Pan.click()
time.sleep(1)
Agency_name = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAgencyName")
Agency_name.send_keys("New_Agency")
time.sleep(1)
Act_No = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtActRegistrationNo")
Act_No.send_keys("NA")
#time.sleep(1)
Authority = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$ddlRegisteringAuthority")
option1 = Select(Authority)
option1.select_by_value("Deputy Registrar of Societies")
time.sleep(2)
TIN = driver.find_element(By.ID, "ctl00_ctl00_cphBody_cphBody_chkTinNotRequre")
TIN.click()
TAN = driver.find_element(By.ID, "ctl00_ctl00_cphBody_cphBody_chkTanNotRequre")
TAN.click()
Block_No = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAddress1")
Block_No.send_keys("NA")
Road = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAddress2")
Road.send_keys("NA")
Area = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAddress3")
Area.send_keys("NA")
City = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtCity")
City.send_keys("Delhi")
State = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$ddlSate")
option2 = Select(State)
option2.select_by_value("9")
time.sleep(3)
District = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$ddlDistrict")
option3 = Select(District)
option3.select_by_value("116")
time.sleep(1)
Pin_code = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtPinCode")
Pin_code.send_keys("110001")
Person = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtContactPerson")
Person.send_keys("NA")
Designation = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtDesignation")
Designation.send_keys("Tester")
Phone_No = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtPhone")
Phone_No.send_keys("99999999")
checkbox = driver.find_element(By.ID, "ctl00_ctl00_cphBody_cphBody_chkAltPhone")
checkbox.click()
Mobile_No = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtMobileNo")
Mobile_No.send_keys("9999999999")
Email = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtEmail")
Email.send_keys("tester15@gmail.com")
time.sleep(1)
Submit = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$btnNext")
Submit.click()
time.sleep(3)
Scheme = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$ddlScheme")
option4 = Select(Scheme)
option4.select_by_value("21376")
time.sleep(2)
Check_SNA = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$btnLoadBankDetails")
Check_SNA.click()
time.sleep(2)
actions.scroll_by_amount(0,900).perform()
time.sleep(3)
Select_Branch = driver.find_element(By.LINK_TEXT, "Select Branch")
Select_Branch.click()
time.sleep(3)
driver.switch_to.window(driver.window_handles[1])
time.sleep(3)
driver.find_element(By.NAME,'btnSearch').click()
time.sleep(5)
Branch = driver.find_element(By.XPATH,'//*[@id="grdvBanks"]/tbody/tr[2]/td/a')
Branch.click()
driver.switch_to.window(driver.window_handles[0])
time.sleep(3)
actions.scroll_by_amount(0,900).perform()
time.sleep(2)
Account = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAccountNo")
Account.send_keys("123123")
AgencyNameasBranch = driver .find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$txtAgencyNamePerBranch")
AgencyNameasBranch.send_keys("NewAgency")
AddBank = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$btnAddAnother")
AddBank.click()
time.sleep(2)
Termsandconditions = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$chkAccept")
Termsandconditions.click()
time.sleep(3)
Submit2 = driver.find_element(By.NAME, "ctl00$ctl00$cphBody$cphBody$btnSave")
Submit2.click()
time.sleep(10)

driver.quit()